Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://19256.cache.armorgames.com/files/games/erase-box-19256/index.html?v=1653005419
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://19256.cache.armorgames.com/files/games/erase-box-19256/index.html?v=1653005419
UUID: 73b40f2f-f783-4b29-a1ca-099fb508f210
Group: ""
Additional Applications: {}
